config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

    


  resources :conversations, except: [:edit] do
    collection do
      post 'create_new_message'
      get 'get_recent_messages'
      get 'show_chat_rooms'
      get 'get_users_in_conversation'
    end
  end

  resources :messages
  resources :boards
  resources :board_threads, except: [:index]

  resources :photo_albums
  resources :photos do
    collection do
      delete 'delete_photo'
    end
  end

  resources :posts do
    collection do
      get 'get_recent_posts'
    end
  end

  resources :users, only: [:show]
  devise_for :users, path_prefix: 'd', controllers:
  {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  mount ActionCable.server => '/cable'

  resources :find_a_friend, only: [] do
    collection do
      get 'get_friends_list'
      get 'get_pending_friends'
      get 'get_blocked_friends'
      get 'get_requested_friends'

      patch 'send_friend_request'
      put 'send_friend_request'

      put 'block_friend'
      patch 'block_friend'

      put 'unblock_friend'
      patch 'unblock_friend'

      get 'find_friends'
      get 'get_entire_friends_list'

      put 'remove_friend'
      patch 'remove_friend'

      put 'accept_friend_request'
      patch 'accept_friend_request'
    end
  end

  get 'api/status', controller: 'api', action: 'status'
  post 'delete_multiple_threads', controller: 'admin', action: 'delete_multiple_threads'
  post 'delete_threads_and_ban_users', controller: 'admin', action: 'delete_threads_and_ban_users'
  
  post 'delete_multiple_posts', controller: 'admin', action: 'delete_multiple_posts'
  post 'delete_posts_and_ban_users', controller: 'admin', action: 'delete_posts_and_ban_users'

  root 'home#index'
end

app/models/conversation.rb
# frozen_string_literal: true

class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_and_belongs_to_many :users
end

app/controllers/conversations_controller.rb
# frozen_string_literal: true

class ConversationsController < ApplicationController
  before_action :set_conversation, only: %i[show edit update destroy]
  # before_action :logged_in?

  def logged_in?
    unless user_signed_in?
      redirect_to root_path, notice: 'You must be logged in to view this page.'
    end
  end

  def show_chat_rooms
    render 'conversations/chatrooms'
  end

  def create_new_message
    convo = Conversation.find params[:conversation_id]

    if convo.users.include? current_user
      message_body = params[:message_body]
      message = Message.create!(first_name: params[:first_name], user: current_user, conversation_id: convo.id, message_body: message_body)

      convo.messages << message unless message.nil?

      render json: { status: 'ok' }
    else
      render json: { status: 'fail' }
    end
  end

  def get_recent_messages
    convo = Conversation.find params[:conversation_id]
    @messages = nil
    @page = params[:page].to_i

    if @page * 50 > convo.messages.count
      @messages = convo.messages.order('created_at ASC').last(convo.messages.count)
      render json: { messages: @messages }
    else
      if convo.users.include? current_user
        # @messages = convo.messages.paginate(page: params[:page], per_page: 50).order("created_at ASC")
        @messages = convo.messages.order('created_at ASC').last(50 * @page)

      elsif !convo.topic.nil?
        # @messages = convo.messages.paginate(page: params[:page], per_page: 50).order("created_at ASC")
        @messages = convo.messages.order('created_at ASC').last(50 * @page)
      end

      render json: { messages: @messages }
    end
  end

  def get_users_in_conversation
    convo = Conversation.find params[:conversation_id]
    @users = nil

    @users = convo.users if convo.users.include? current_user

    render json: { users: @users }, except: [:email]
  end

  # GET /conversations
  # GET /conversations.json
  def index
    @conversations = current_user.conversations
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
    @conversation = Conversation.find(params[:id])
    @messages = @conversation.messages
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit; end

  # POST /conversations
  # POST /conversations.json
  def create
    @conversation = Conversation.new

    respond_to do |format|
      if @conversation.save

        recipient_user = User.find conversation_params[:recipient_id]
        @conversation.users << current_user unless current_user.nil?
        @conversation.users << recipient_user unless recipient_user.nil?

        format.html { redirect_to @conversation, notice: 'Conversation was successfully created.' }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_conversation
    @conversation = Conversation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def conversation_params
    params.fetch(:conversation, {}).permit(:sender_id, :recipient_id)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= form_with(model: conversation, local: true) do |f| %>
  <%= f.select :recipient_id, current_user.friends.collect {|c| [ c.first_name, c.id ] } %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conversations/chatrooms.html.erb
<% CS.states(:us).each do |k,v| %>
    <% convo = Conversation.find_by(topic: k) %>
    <%= link_to v, convo %>
    <br />
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<h1>New dm </h1>
<%= link_to 'Start New Conversation', new_conversation_path %> <br />

<h2>Current Conversations</h2>
<% @conversations.each do |convo| %>
    <% if convo.topic == "" %>
        <%= link_to convo.users.last.first_name, convo %>
    <% end %>
<% end %>

app/views/conversations/new.html.erb
<%= form_with model: @conversation do |f| %>
  <% if @conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(test.errors.count, "error") %> prohibited this test from being saved:</h2>

      <ul>
      <% test.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>    

    <%= f.collection_select :recipient, current_user.friends.order(:first_name),:id, :first_name, include_blank: true %>
    <%= f.label :sender, current_user.id %>
    <%= f.submit %>

<% end %>

app/views/conversations/show.html.erb
<% if @conversation.topic != nil %>
<h1 class="text-center"><%= @conversation.topic %></h1>
<% end %>

<%= react_component("Conversation", {user_profile_path: '/users/' , user_id: current_user.id, conversation_id: @conversation.id.to_s, first_name: current_user.first_name}) %>