config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

    


  resources :conversations, except: [:edit] do
    collection do
      post 'create_new_message'
      get 'get_recent_messages'
      get 'show_chat_rooms'
      get 'get_users_in_conversation'
    end
  end

  resources :messages
  resources :boards
  resources :board_threads, except: [:index]

  resources :photo_albums
  resources :photos do
    collection do
      delete 'delete_photo'
    end
  end

  resources :posts do
    collection do
      get 'get_recent_posts'
    end
  end

  resources :users, only: [:show]
  devise_for :users, path_prefix: 'd', controllers:
  {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  mount ActionCable.server => '/cable'

  resources :find_a_friend, only: [] do
    collection do
      get 'get_friends_list'
      get 'get_pending_friends'
      get 'get_blocked_friends'
      get 'get_requested_friends'

      patch 'send_friend_request'
      put 'send_friend_request'

      put 'block_friend'
      patch 'block_friend'

      put 'unblock_friend'
      patch 'unblock_friend'

      get 'find_friends'
      get 'get_entire_friends_list'

      put 'remove_friend'
      patch 'remove_friend'

      put 'accept_friend_request'
      patch 'accept_friend_request'
    end
  end

  get 'api/status', controller: 'api', action: 'status'
  post 'delete_multiple_threads', controller: 'admin', action: 'delete_multiple_threads'
  post 'delete_threads_and_ban_users', controller: 'admin', action: 'delete_threads_and_ban_users'
  
  post 'delete_multiple_posts', controller: 'admin', action: 'delete_multiple_posts'
  post 'delete_posts_and_ban_users', controller: 'admin', action: 'delete_posts_and_ban_users'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# frozen_string_literal: true

class Board < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates_uniqueness_of :name

  has_many :board_threads
end

app/models/board_thread.rb
class BoardThread < ApplicationRecord
    belongs_to :board
    belongs_to :user

    has_many :posts

    validates :title, presence: true
    validates :body, presence: true
end

app/models/conversation.rb
# frozen_string_literal: true

class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_and_belongs_to_many :users
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord

    extend Geocoder::Model::ActiveRecord
    geocoded_by :address

    #validates :zipcode, zipcode: { country_code: :us }

    has_one :user

    def address
        address + city + country
    end
    
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  
  validates_presence_of :message_body, :conversation_id, :user_id

end

app/models/photo.rb
class Photo < ApplicationRecord
    include FafEnums

    has_one_attached :image
    belongs_to :photo_album

    validates :title, presence: true
    validates :description, presence: true
end

app/models/photo_album.rb
class PhotoAlbum < ApplicationRecord
    include FafEnums

    has_many :photos
    belongs_to :user

    validates :title, presence: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  include FafEnums

  belongs_to :user
  belongs_to :board_thread, optional: true
  
  validates :body, presence: true

    def created_at_js
        created_at.strftime()
    end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include FafEnums

  attr_accessor :current_password

  devise :database_authenticatable,
         :confirmable,
         :registerable,
         :rememberable,
         :trackable,
         :timeoutable,
         :validatable,
         :lockable,
         :recoverable,
         :omniauthable, omniauth_providers: %i[discord]

  def self.from_omniauth(auth)
    # Either create a User record or update it based on the provider (Google) and the UID
    User.where(provider: auth.provider, email: auth.info.email).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid

      user.token = auth.credentials.token
      user.expires = auth.credentials.expires
      user.expires_at = auth.credentials.expires_at
      user.refresh_token = auth.credentials.refresh_token
      user.first_name = 'Unknown'
      user.last_name = 'Name'
      if user.password.blank?
        user.password = Devise.friendly_token[0, 20]
      else
        user.password = user.password
      end
      
      user.skip_confirmation!
      user.save!
    end
  end

  def self.email_required?
    super && provider.blank?
  end

  def self.password_required?
    super && provider.blank?
  end

  has_one_attached :profile_picture

  # validates :first_name, presence: true
  # validates :last_name, presence: true

  has_friendship
  acts_as_follower
  acts_as_liker

  has_and_belongs_to_many :conversations

  has_many :posts
  has_many :photo_albums

  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

  belongs_to :location, optional: true

  enum gender:
  {
    male: 0,
    female: 1,
    mtf: 2,
    ftm: 3,
    non_binary: 4
  }

  validate :validate_age

  private

  def validate_age
    if birthdate.present? && birthdate > 18.years.ago
      errors.add(:birthdate, 'You should be over 18 years old.')
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  def status
    render json: { data: 'ok' }
  end

end

app/controllers/boards_controller.rb
# frozen_string_literal: true

class BoardsController < ApplicationController

  breadcrumb 'Boards', :boards_path, only: [:show]
    
  def index
    @boards = Board.all

    @page_title       = 'Boards'
    @page_description = 'uwuanimu.com message boards.'
  end

  def show
    @board = Board.find_by(name: params[:id])

    if @board.board_threads.count.positive?
        @threads = @board.board_threads.order('created_at DESC') 
    end

    breadcrumb @board.name, board_path(@board)
    @page_title       = @board.name
    @page_description = @board.description
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/index.html.erb
<div class="list-group">
    <% @boards.each do |board| %>
        <%= link_to board, class: 'list-group-item list-group-item-action flex-column align-items-start' do %>
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1"><%= board.name %></h5>
            </div>
            <p class="mb-1"><%= board.description %></p>
        <% end %>
    <% end %>
</div>

app/views/boards/show.html.erb
<ul class="list-group">
<nav aria-label="breadcrumb">
  <ol class='breadcrumb'>
    <% breadcrumb_trail do |crumb| %>
      <li class="breadcrumb-item <%= crumb.current? ? 'active' : '' %>">
        <%= link_to crumb.name, crumb.url, (crumb.current? ? {'aria-current' => 'page'} : {}) %>
      </li>
    <% end %>
  </ol>
</nav>

    <%= button_to "New Thread", new_board_thread_path, params: {board: @board.id} , method: :get, class: 'btn btn-primary' %>
    <br />
    
    <% unless @threads.nil? %>
    
        <% @threads.each do |thread| %>
            <% if thread.soft_deleted? %>
              <% if user_signed_in? %>
                <% if !current_user.admin? %>
                  <% next %>
                <% end %>
              <% else %>
                <% next %>
              <% end %>
            <% end %>

            <li class="list-group-item clearfix text-dark">
              <% if !current_user.nil? && current_user.admin? %>
                  <%= check_box_tag "thread_ids[]", thread.id %>
                    <% if thread.soft_deleted? %>
                      <small>THREAD IS ONLY VIEWABLE TO ADMINS</small>
                    <% end %>
                  <% end %>
              <%= thread.user.first_name %>

              <%= link_to thread, class: 'link_no_styling' do %>
                  <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1"><%= thread.title %></h5>
                  <small><%= thread.created_at %></small>
                  </div>
                  <p class="mb-1"><%= thread.body %></p>
              <% end %>
            </li>
        <% end %>
    
      <% if !current_user.nil? && current_user.admin? %>
        <%= label_tag "Admin Actions" %> <br />
        <%= form_with(url: delete_multiple_threads_path) do |f| %>
          <div class="btn-group-vertical">
              <%= f.button 'Delete', class: 'btn btn-danger' %>
              <%= f.hidden_field :thread_ids, multiple: true %>
          </div>
        <% end %>

        <%= form_with(url: delete_threads_and_ban_users_path) do |f| %>
          <div class="btn-group-vertical">
              <%= f.button 'Delete and Ban User', class: 'btn btn-danger' %>
              <%= f.hidden_field :thread_ids, multiple: true %>
          </div>
        <% end %>

        DevNote: All checkboxed threads will have the same action applied to them (ban user, or delete user..etc).
      <% end %>

    <% end %>

    <% if @threads.nil? %>
        No threads on this board currently.
    <% end %>
    
    <br />
</ul>

<script type="text/javascript">
$(document).ready(function()
{
  var checked_checkboxes = []

  $("input[type='checkbox']").on('change', function()
  {
    if (this.checked)
    {
      checked_checkboxes.push(this.value)
      $("input[type='hidden'][id='thread_ids'").val(checked_checkboxes)
    }
    else 
    {
      var base_value = this.value
      var filteredArray = checked_checkboxes.filter(function(value, index, arr){
          return value != base_value
      })
      checked_checkboxes = filteredArray
      $("input[type='hidden'][id='thread_ids']").val(checked_checkboxes)
    }
  })

})
</script>